twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        footer_service: '@App\Site\Infrastructure\UI\Web\Twig\FooterService'

when@test:
    twig:
        strict_variables: true
