version: '3.8'

services:
  database:
    container_name: 'donbert-database'
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: wrz4jk94
      MYSQL_DATABASE: donbert
      MYSQL_USER: donbert
      MYSQL_PASSWORD: wrz4jk94
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: 'donbert-php'
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/symfony_docker
    depends_on:
      - database
  nginx:
    container_name: 'donbert-nginx'
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - .:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
  db_admin:
    image: phpmyadmin/phpmyadmin:5
    container_name: 'donbert-db-admin'
    ports:
      - '30107:80'
    environment:
      PMA_HOST: database
    depends_on:
      - database
      
    volumes:
      - db_admin_data:/var/www/html
volumes:
  db_admin_data:
