shared:
    resource:
        path: ../src/Shared/Infrastructure/UI/Web/Controller
        namespace: App\Shared\Infrastructure\UI\Web\Controller
    type: attribute
product:
    resource:
        path: ../src/Product/Infrastructure/UI/Web/Controller
        namespace: App\Product\Infrastructure\UI\Web\Controller
    type: attribute