shared:
    resource:
        path: ../src/Shared/Infrastructure/Controller
        namespace: App\Shared\Infrastructure\Controller
    type: attribute
product:
    resource:
        path: ../src/Product/Infrastructure/Controller
        namespace: App\Product\Infrastructure\Controller
    type: attribute