
site:
    resource:
        path: ../src/Site/Infrastructure/UI/Web/Controller
        namespace: App\Site\Infrastructure\UI\Web\Controller
    type: attribute
admin_product:
    resource:
        path: ../src/Product/Infrastructure/UI/Web/Controller/Admin
        namespace: App\Product\Infrastructure\UI\Web\Controller\Admin
    type: attribute
product:
    resource:
        path: ../src/Product/Infrastructure/UI/Web/Controller
        namespace: App\Product\Infrastructure\UI\Web\Controller
    type: attribute
newsletter:
    resource:
        path: ../src/Newsletter/Infrastructure/UI/Web/Controller
        namespace: App\Newsletter\Infrastructure\UI\Web\Controller
    type: attribute